%global debug_package %{nil}
# Bundled FFmpeg 8 + ONNX Runtime under /opt/concat-unstable/lib (found via
# $ORIGIN/lib RUNPATH, same as upstream's own bundles) - exclude them from
# automatic dependency generation; system sonames still auto-resolve.
%global __requires_exclude_from ^/opt/concat-unstable/.*$
%global __provides_exclude_from ^/opt/concat-unstable/.*$
%global commit          948b6db90448b2f0cda865f38a614d18353ff557
%global shortcommit     948b6db
%global gitdate         20261009170713
%global base_version    0.2.6
Name:           concat-unstable
Version:        %{base_version}+git%{gitdate}.%{shortcommit}
Release:        0
Summary:        Free and open source video editor (main-branch snapshot)
License:        AGPL-3.0-or-later
Group:          Productivity/Graphics/Video
URL:            https://github.com/jub0t/concat
# Unified snapshot tarball generated by update.sh: upstream main tree at
# the pinned commit plus vendored crates, BtbN FFmpeg 8.1 tree and ONNX
# 1.28.0 libs (top dir concat-<commit>/). Single source keeps %prep and
# the Debian orig trivially in sync (cf. lazyvim-git generated tarballs).
Source0:        %{name}-%{version}.tar.gz
BuildRequires:  cargo
# NOTE: no `rustc` BuildRequires - no such package exists on Tumbleweed
# (verified `zypper se --match-exact rustc` = 0 hits); `cargo` requires
# the Rust toolchain, so the compiler is always present.
BuildRequires:  pkgconfig(openssl)
BuildRequires:  gcc-c++
BuildRequires:  make
BuildRequires:  cmake
BuildRequires:  pkgconf
BuildRequires:  libclang13
BuildRequires:  fontconfig-devel
BuildRequires:  freetype2-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  Mesa-libGL-devel
BuildRequires:  gtk3-devel
BuildRequires:  alsa-devel
BuildRequires:  desktop-file-utils
BuildRequires:  hicolor-icon-theme
# Runtime set mirrors the stable repack (same GUI stack; NEEDED-derived
# system libs additionally auto-resolve since only /opt paths are
# excluded). Bundled libav*/libonnxruntime resolve via $ORIGIN/lib.
Requires:       Mesa-libGL1
Requires:       fontconfig
Requires:       gtk3
Requires:       hicolor-icon-theme
Requires:       libasound2
Requires:       libfreetype6
Requires:       libxkbcommon-x11-0
Requires:       libxkbcommon0
ExclusiveArch:  x86_64

%description
Concat main-branch snapshot: free and open source cross-platform video
editor (timeline editing, effects, transitions, titles, captions and
speech) with FFmpeg underneath and hardware-accelerated preview and
export. Tracks upstream main past the latest release; base version plus
the newest commit show in the package version.

%prep
%autosetup -n concat-%{commit}

%build
# Offline vendored Rust build. Toolchain floor is rust 1.93 (workspace
# rust-toolchain.toml); Tumbleweed ships newer. Env mirrors upstream's own
# Linux CI: BtbN FFmpeg tree via FFMPEG_DIR, Microsoft ONNX build via
# ORT_LIB_LOCATION + dynamic preference, rpath $ORIGIN/lib with old-style
# DT_RPATH so bundled libs resolve transitively at runtime.
# SKIA RESOLVED (2026-10-09): Slint's Skia renderer needs the rust-skia
# binary cache; the exact {tag}/{key} came from the OBS log's
# "TRYING TO DOWNLOAD" line and the archive is prefetched into
# skia-cache/ by update.sh step 4b (SKIA_BINARIES_URL=file://... below).
# If skia-bindings bumps, refresh the key per update.sh's procedure.
export CARGO_NET_OFFLINE=true
export ORT_SKIP_DOWNLOAD=1
# NOTE (2026-10-09): %%autosetup -n concat-%%{commit} unpacks to
# %%{_builddir}/concat-%%{commit}, NOT %%{_builddir}/%%{name}-%%{version} -
# the env dirs must use the real top dir (wrong path broke the first
# build). (Double-%%: a bare %macro in a comment WOULD expand - that
# exact mistake injected a literal %setup line into %build and broke
# the second build with "fg: no job control".)
export FFMPEG_DIR="%{_builddir}/concat-%{commit}/ffmpeg-dev"
export ORT_LIB_LOCATION="%{_builddir}/concat-%{commit}/onnxlib"
export ORT_PREFER_DYNAMIC_LINK=1
# Skia prebuilt binaries (rust-skia binary cache, tag/key read from the
# OBS log's "TRYING TO DOWNLOAD" line - never guessed). The archive is
# prefetched into skia-cache/ by update.sh; file:// is read verbatim
# (skia-bindings utils::download supports file:// with empty hostname).
export SKIA_BINARIES_URL="file://%{_builddir}/concat-%{commit}/skia-cache/skia-binaries-b7f043e0b1e2a850e702-x86_64-unknown-linux-gnu-ganesh-gl-jpegd-jpege-pdf-vulkan.tar.gz"
# sherpa-onnx static libs (sherpa-onnx-sys build.rs): SHERPA_ONNX_ARCHIVE_DIR
# is copied to the cargo cache instead of downloading (offline DNS fails).
# Archive name embeds sherpa-onnx-sys's CARGO_PKG_VERSION - refresh with
# update.sh step 4c when it changes (a stale name errors loudly, no guess).
export SHERPA_ONNX_ARCHIVE_DIR="%{_builddir}/concat-%{commit}/sherpa-cache"
export RUSTFLAGS="-C link-arg=-Wl,-rpath,\$ORIGIN/lib -C link-arg=-Wl,--disable-new-dtags"
cd src && cargo build --offline --frozen --release --bin concat

%install
install -d -m 0755 %{buildroot}/opt/concat-unstable/lib
install -m 0755 src/target/release/concat %{buildroot}/opt/concat-unstable/concat-unstable
cp -a ffmpeg-dev/lib/lib*.so* %{buildroot}/opt/concat-unstable/lib/
cp -a onnxlib/libonnxruntime.so* %{buildroot}/opt/concat-unstable/lib/

install -d -m 0755 %{buildroot}%{_bindir}
cat > %{buildroot}%{_bindir}/concat-unstable <<'EOF'
#!/bin/sh
exec /opt/concat-unstable/concat-unstable "$@"
EOF
chmod 0755 %{buildroot}%{_bindir}/concat-unstable

install -d -m 0755 %{buildroot}%{_datadir}/applications
cat > %{buildroot}%{_datadir}/applications/concat-unstable.desktop <<'EOF'
[Desktop Entry]
Type=Application
Name=Concat (Unstable)
Comment=Video editor - main branch snapshot
Exec=/usr/bin/concat-unstable %U
Icon=concat-unstable
Terminal=false
Categories=AudioVideo;Video;
EOF

install -d -m 0755 %{buildroot}%{_datadir}/icons/hicolor/256x256/apps
install -m 0644 assets/icons/concat_logo_256.png \
    %{buildroot}%{_datadir}/icons/hicolor/256x256/apps/concat-unstable.png

%check
desktop-file-validate %{buildroot}%{_datadir}/applications/concat-unstable.desktop

%files
%license LICENSE
%{_bindir}/concat-unstable
%{_datadir}/applications/concat-unstable.desktop
%{_datadir}/icons/hicolor/256x256/apps/concat-unstable.png
/opt/concat-unstable/

%changelog
